codem-schedule/config/routes.rb
Scheduler::Application.routes.draw do
  namespace :api do
    resources :jobs do
      collection do
        get :scheduled
        get :processing
        get :on_hold
        get :success
        get :completed
        get :failed
        delete :purge
      end

      member do
        post :retry
      end

      member do
        resources :state_changes
        resources :notifications
      end
    end

    get '/probe'   => 'api#probe'
    get '/schedule' => 'scheduler#schedule'

    resources :presets

    resources :hosts

    get '/statistics' => 'statistics#show'
  end

  resources :jobs

  resources :presets, :hosts

  root :to => 'dashboard#show'
end

codem-schedule/app/models/preset.rb
class Preset < ActiveRecord::Base
  has_many :jobs

  validates :name, presence: true, uniqueness: true

  validate :should_have_params_or_thumbnail_options
  validate :thumbnail_options, :valid_json_options, if: proc { |p| p.thumbnail_options.present? }

  def self.from_api(attributes)
    attributes = attributes[:preset] if attributes[:preset]
    create(name: attributes['name'],
           parameters: attributes['parameters'],
           thumbnail_options: attributes['thumbnail_options'])
  end

  private

  def valid_json_options
    JSON.parse(thumbnail_options)
    true
  rescue JSON::ParserError
    errors.add(:thumbnail_options, 'must be valid JSON')
    false
  end

  def should_have_params_or_thumbnail_options
    return true if parameters.present? || thumbnail_options.present?
    errors.add(:base, 'Either parameters or thumbnail options should be specified')
  end
end

codem-schedule/app/controllers/api/presets_controller.rb
# = Presets Controller
#
# A preset represents command line options for ffmpeg sent to the Transcoder
module Api
  class PresetsController < ApiController
    # == Returns a list of presets
    #
    # == Example:
    #   $ curl http://localhost:3000/api/presets
    #
    #   [
    #     {"preset":{
    #       "created_at":"2011-05-09T11:59:53Z",
    #       "id":1,
    #       "name":"h264",
    #       "parameters":"-acodec libfaac -ab 96k -ar 44100 -vcodec libx264 -vb 416k -vpre slow -vpre baseline -s 320x180 -y",
    #       "thumbnail_options":null,
    #       "updated_at":"2011-05-09T11:59:53Z"}
    #     }
    #   ]
    def index
      respond_with Preset.all
    end

    # == Creates a preset
    #
    # Creates a preset using the specified parameters, which are all required. If the request was valid,
    # the created preset is returned. If the request could not be completed, a list of errors will be returned.
    #
    # === Parameters
    # Required:
    # <tt>name</tt>:: Name of the preset
    # <tt>params</tt>:: Parameters to use
    # Optional:
    # <tt>thumbnail_options</tt>:: Thumbnail options to use
    #
    # === Response codes
    # <tt>success</tt>:: <tt>201 created</tt>
    # <tt>failed</tt>::  <tt>406 Unprocessable Entity</tt>
    #
    # === Example
    #   $ curl -d 'name=webm&parameters=params' http://localhost:3000/api/presets
    #
    #   {"preset":{
    #     "created_at":"2011-05-10T14:44:07Z",
    #     "id":3,
    #     "name":"webm",
    #     "parameters":"params",
    #     "thumbnail_options":null,
    #     "updated_at":"2011-05-10T14:44:07Z"}
    #   }
    def create
      preset = Preset.from_api(params)

      if preset.valid?
        respond_with preset, location: api_preset_url(preset) do |format|
          format.html { redirect_to presets_path }
        end
      else
        respond_with preset do |format|
          format.html do
            @preset = preset
            render '/presets/new'
          end
        end
      end
    end

    # == Displays a preset
    #
    # === Parameters
    # <tt>id</tt>:: Id of the preset to display
    #
    # === Example
    #   $ curl http://localhost:3000/api/presets/1
    #
    #   {"preset":{
    #     "created_at":"2011-05-10T14:44:07Z",
    #     "id":3,
    #     "name":"webm",
    #     "parameters":"params",
    #     "thumbnail_options":null,
    #     "updated_at":"2011-05-10T14:44:07Z"}
    #   }
    def show
      respond_with Preset.find(params[:id])
    end

    # == Updates a preset
    #
    # === Parameters
    # <tt>id</tt>:: Id of the preset to update
    # <tt>name</tt>:: Name of the preset
    # <tt>parameters</tt>:: Parameters of the preset
    # <tt>thumbnail_options</tt>:: Thumbnail options
    #
    # === Example
    #
    #   $ curl -XPUT -d 'name=h264&parameters=params' http://localhost:3000/api/presets/1
    #   {} # HTTP Status: 200 OK
    def update
      if params[:preset]
        params[:name] = params[:preset][:name]
        params[:parameters] = params[:preset][:parameters]
        params[:thumbnail_options] = params[:preset][:thumbnail_options]
      end

      preset = Preset.find(params[:id])

      if preset.update_attributes(name: params[:name], parameters: params[:parameters], thumbnail_options: params[:thumbnail_options])
        respond_with preset, location: api_preset_url(preset) do |format|
          format.html { redirect_to presets_path }
        end
      else
        respond_with preset do |format|
          format.html do
            @preset = preset
            render '/presets/edit'
          end
        end
      end
    end

    # == Deletes a preset
    #
    # === Parameters
    # <tt>id</tt>:: Id of the preset to delete
    #
    # === Example
    #
    #   $ curl -XDELETE http://localhost:3000/api/presets/1
    #   {} # HTTP Status: 200 OK
    def destroy
      preset = Preset.find(params[:id])
      preset.destroy
      respond_with preset do |format|
        format.html { redirect_to presets_path }
      end
    end
  end
end

codem-schedule/app/controllers/presets_controller.rb
class PresetsController < ApplicationController
  def index
    @presets = Preset.all
  end

  def new
    @preset = Preset.new
  end

  def edit
    @preset = Preset.find(params[:id])
  end
end

codem-schedule/app/views/presets/_form.html.erb
<%= form_for [:api, @preset], class: 'form-horizontal' do |f| %>
	<% if @preset.errors.any? %>
    <div class="panel panel-warning">
      <div class="panel-heading">
        Preset could not be saved
      </div>

      <div class="panel-body">
        <ul>
          <% @preset.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <fieldset>
    <div class="control-group">
      <%= f.label :name, class: 'control-label required' %>
      <div class="controls">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :parameters, nil, class: 'control-label required' %>
      <div class="controls">
        <%= f.text_field :parameters, class: 'form-control' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :thumbnail_options, class: 'control-label required' %>
      <div class="controls">
        <%= f.text_field :thumbnail_options, class: 'form-control' %>
      <a href="#thumbnail_help" role="button" class="btn" data-toggle="modal">Help</a>
      </div>
    </div>

  </fieldset>

  <div class="form-actions"> 
    <%= f.submit class: 'btn btn-primary' %> or 
    <%= link_to 'Cancel', presets_path %>
  </div>
<% end %>

<div class="modal fade" id="thumbnail_help">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Thumbnail options</h3>
      </div>
      <div class="modal-body">
        <p>
        It's possible to automatically generate thumbnails while transcoding the input file. These options can be specified for each preset, and use the following syntax:
        </p>
        <ul>
          <li>Either "percentages" or "seconds" (but not both at the same time), valid options are:</li>
          <ul>
   		      <li><p>A single percentage, this will trigger a thumbnail every x.<pre>{ "percentages": 0.1 }</pre> will generate thumbnails at 0%, 10%, 20%, [...], 100%.</p></li>
   		      <li><p>An array of explicit percentages, this will trigger thumbnails only at the specified positions.<pre>{ "percentages": [0.25, 0.5, 0.75] }</pre> will generate thumbnails at 25%, 50% and 75%.</p></li>
   		      <li>A single offset in seconds, this will trigger a thumbnail every x seconds.<pre>{ "seconds": 10 }</pre> will generate thumbnails at 0 seconds, 10 seconds, 20 seconds, etc., until the end of the source file.</li>
   		      <li><p>An array of explicit offsets, this will trigger thumbnails only at the specified positions.<pre>{ "seconds": [30, 60, 90] }</pre> will generate thumbnails at 30 seconds, 60 seconds and 90 seconds.</p></li>
          </ul>
          <ul>
            <li>A size can be specified in pixels (width x height). If omitted it will generate thumbnails the size of the source video. (optional)</li>
            <li>A format for the thumbnails. The format must be supported by your ffmpeg binary. If omitted it will generate thumbnails in the JPEG format. Most people will use either "jpg" or "png". (optional)</li>
          </ul>		
        </ul>
      </ul>
      <p>See <a href="https://github.com/madebyhiro/codem-transcode#usage">github.com/madebyhiro/codem-transcode#usage</a> for more info.</p>
    </div>
    <div class="modal-footer">
      <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>
</div>
</div>

codem-schedule/app/views/presets/_preset.html.erb
<%= content_tag_for :div, preset do %>
  <h4><%= preset.name %></h4>
  <pre><%= preset.parameters %></pre>
  <%= link_to 'Edit', edit_preset_path(preset), class: 'btn btn-mini' %> 
  <%= link_to 'Delete', api_preset_path(preset), class: 'btn btn-mini', method: :delete, data: { confirm: 'Are you sure you want to delete this preset?' } %>
<% end %>

codem-schedule/app/views/presets/edit.html.erb
<% title 'Edit preset' %>

<%= render "/presets/form" %>

codem-schedule/app/views/presets/index.html.erb
<% title 'Presets' %>

<%= section 'Presets', class: 'presets' do %>
  <%= render @presets %>
<% end %>

<div class="form-actions">
  <%= link_to 'New preset', new_preset_path, class: 'btn btn-primary' %>
</div>

codem-schedule/app/views/presets/new.html.erb
<% title 'New preset' %>

<%= render "/presets/form" %>