codem-schedule/config/routes.rb
Scheduler::Application.routes.draw do
  namespace :api do
    resources :jobs do
      collection do
        get :scheduled
        get :processing
        get :on_hold
        get :success
        get :completed
        get :failed
        delete :purge
      end

      member do
        post :retry
      end

      member do
        resources :state_changes
        resources :notifications
      end
    end

    get '/probe'   => 'api#probe'
    get '/schedule' => 'scheduler#schedule'

    resources :presets

    resources :hosts

    get '/statistics' => 'statistics#show'
  end

  resources :jobs

  resources :presets, :hosts

  root :to => 'dashboard#show'
end

codem-schedule/app/models/host.rb
class Host < ActiveRecord::Base
  has_many :jobs

  validates :name, :url, presence: true

  before_save :normalize_url

  def self.from_api(opts)
    opts = opts[:host] if opts[:host] # Rails' forms wraps hashes in a root tag
    host = new(name: opts['name'], url: opts['url'])
    host.update_status if host.save
    host
  end

  def self.with_available_slots
    all.map(&:update_status).select { |h| h.available_slots > 0 }.shuffle
  end

  def update_status
    return self if status_updated_at && status_updated_at > 10.seconds.ago

    self.available = false
    self.status_updated_at = Time.current

    attrs = Transcoder.host_status(self)
    if attrs
      self.total_slots          = attrs['max_slots']
      self.available_slots      = attrs['free_slots']
      self.available            = true
    end

    save

    self
  end

  private

  def normalize_url
    self.url = url.to_s.gsub(/\/$/, '')
  end
end

codem-schedule/app/controllers/api/hosts_controller.rb
# = Hosts controller
#
# A host represents an instance of a Transcoder, defined by name and url
module Api
  class HostsController < ApiController
    # == Displays a list of hosts
    #
    # All returned hosts will ahve their statuses updated to provide an up-to-date view of their slots.
    #
    # === Example
    #   $ curl http://localhost:3000/api/hosts
    #
    #   [
    #      {"host":{
    #        "available":true,
    #        "available_slots":1,
    #        "created_at":"2011-05-09T11:59:52Z",
    #        "id":1,
    #        "name":"Localhost",
    #        "total_slots":1,
    #        "updated_at":"2011-05-09T13:53:31Z",
    #        "url":"http://127.0.0.1:8080"}
    #      }
    #    ]
    def index
      hosts = Host.all
      hosts.map(&:update_status)
      respond_with hosts
    end

    # == Creates a host
    # Creates a host using the specified parameters, all are required. If the request was valid,
    # the created host is returned. If the request could not be completed, a list of errors will be returned.
    #
    # === Parameters
    # <tt>name</tt>:: The name of the host
    # <tt>url</tt>::  The url of the host
    #
    # === Response codes
    # <tt>success</tt>:: <tt>201 created</tt>
    # <tt>failed</tt>::  <tt>406 Unprocessable Entity</tt>
    #
    # === Example
    #   $ curl -d 'name=transcoder&url=http://transcoder.com' http://localhost:3000/api/hosts
    #
    #   {
    #     "host": {
    #       "available":true,
    #       "available_slots":10,
    #       "created_at":"2011-05-09T15:32:53Z",
    #       "id":6,
    #        "name":"transcoder",
    #        "total_slots":10,
    #        "updated_at":"2011-05-09T15:32:53Z",
    #        "url":"http://transcoder.com"
    #     }
    #   }
    def create
      host = Host.from_api(params)

      if host.valid?
        respond_with host, location: api_host_url(host) do |format|
          format.html { redirect_to hosts_path }
        end
      else
        respond_with host do |format|
          format.html do
            @host = host
            render '/hosts/new'
          end
        end
      end
    end

    # == Shows a specific host
    #
    # The host will have its status updated to provide an up-to-date view of the slots.
    #
    # === Parameters
    # <tt>id</tt>:: The id of the host to show
    #
    # === Example
    #   $ curl http://localhost:3000/api/hosts/1
    #
    #   {
    #      "host":{
    #        "available":true,
    #        "available_slots":1,
    #        "created_at":"2011-05-09T11:59:52Z",
    #        "id":1,
    #        "name":"Localhost",
    #        "total_slots":1,
    #        "updated_at":"2011-05-09T13:53:31Z",
    #        "url":"http://127.0.0.1:8080"}
    #      }
    def show
      host = Host.find(params[:id])
      host.update_status
      respond_with host
    end

    # == Updates a host
    #
    # === Paramdeters
    # <tt>id</tt>:: Id of the host to update
    # <tt>name</tt>:: Name of the host
    # <tt>url</tt>:: Url of the host
    #
    # === Example
    #
    #   $ curl -XPUT -d 'name=h&url=foo.com' http://localhost:3000/api/hosts/1
    #   {} # HTTP Status: 200 OK
    def update
      if params[:host]
        params[:name] = params[:host][:name]
        params[:url]  = params[:host][:url]
      end

      host = Host.find(params[:id])

      if host.update_attributes(name: params[:name], url: params[:url])
        host.update_status
        respond_with host, location: api_host_url(host) do |format|
          format.html { redirect_to hosts_path }
        end
      else
        respond_with host do |format|
          format.html do
            @host = host
            render '/hosts/edit'
          end
        end
      end
    end

    # == Deletes a host
    #
    # === Parameters
    # <tt>id</tt>:: Id of the host to delete
    #
    # === Example
    #
    #   $ curl -XDELETE http://localhost:3000/api/hosts/1
    #   {} # HTTP Status: 200 OK
    def destroy
      host = Host.find(params[:id])
      host.destroy
      respond_with host do |format|
        format.html { redirect_to hosts_path }
      end
    end
  end
end

codem-schedule/app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  def index
    @hosts = Host.all
    @hosts.map(&:update_status)
  end

  def new
    @host = Host.new
  end

  def edit
    @host = Host.find(params[:id])
  end
end

codem-schedule/app/helpers/hosts_helper.rb
module HostsHelper
  def host_name(host)
    return nil unless host

    if host.name.nil?
      host.url
    else
      "#{host.name} (<span class=\"address\">#{host.url}</span>)".html_safe
    end
  end
end

codem-schedule/app/views/hosts/_form.html.erb
<%= form_for [:api, @host], class: 'form-horizontal' do |f| %>

	<% if f.object.errors.any? %>
    <div class="panel panel-warning">
      <div class="panel-heading">
        Host could not be saved
      </div>

      <div class="panel-body">
        <ul>
          <% f.object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>


  <fieldset>
    <div class="control-group">
      <%= f.label :name, nil, class: 'control-label required' %>
      <div class="controls">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :url, nil, class: 'control-label required' %>
      <div class="controls">
        <%= f.text_field :url, class: 'form-control' %>
      </div>
    </div>
  </fieldset>

  <div class="form-actions"> 
    <%= f.submit class: 'btn btn-primary' %> or 
    <%= link_to 'Cancel', hosts_path %>
  </div>
<% end %>

codem-schedule/app/views/hosts/_host.html.erb
<%= content_tag_for :div, host, :class => "#{host.available ? 'success' : 'error'}" do %>
  <div class="alert alert-<%= host.available ? 'success' : 'danger' %>">
    <h3><%= host.name %> (<%= host.available ? 'Available' : 'Not available' %>)</h3>
    <h4><%= host.url %></h4>

    <br/>

    <%= link_to 'Edit', edit_host_path(host), class: 'btn btn-mini' %> 
    <%= link_to 'Delete', api_host_path(host), class: 'btn btn-mini', method: :delete, data: { confirm: 'Are you sure you want to delete this host?' }  %>

    <% if host.available %>
      <table class="table table-condensed">
        <tr>
          <td><span class="badge badge-success"><%= host.available_slots %></span> available slots</td>
        </tr>
        <tr>
          <td><span class="badge badge-info"><%= host.total_slots %></span> total slots</td>
        </tr>
        <tr>
          <td><span class="badge badge-default"><%= host.total_slots - host.available_slots %></span> used slots</td>
        </tr>
      </table>
    <% end %>

  </div>

<% end %>

codem-schedule/app/views/hosts/edit.html.erb
<% title 'Edit host' %>

<%= render "/hosts/form" %>

codem-schedule/app/views/hosts/index.html.erb
<% title 'Hosts' %>

<%= section 'Hosts', class: 'hosts' do %>
  <%= render @hosts %>
<% end %>

<div class="form-actions">
  <%= link_to 'Add a host', new_host_path, class: 'btn btn-primary' %>
</div>

codem-schedule/app/views/hosts/new.html.erb
<% title 'New host' %>

<%= render "/hosts/form" %>