codem-schedule/config/routes.rb
Scheduler::Application.routes.draw do
  namespace :api do
    resources :jobs do
      collection do
        get :scheduled
        get :processing
        get :on_hold
        get :success
        get :completed
        get :failed
        delete :purge
      end

      member do
        post :retry
      end

      member do
        resources :state_changes
        resources :notifications
      end
    end

    get '/probe'   => 'api#probe'
    get '/schedule' => 'scheduler#schedule'

    resources :presets

    resources :hosts

    get '/statistics' => 'statistics#show'
  end

  resources :jobs

  resources :presets, :hosts

  root :to => 'dashboard#show'
end

codem-schedule/app/views/layouts/_help.html.erb
<div class="modal fade" id="help">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Search Help</h3>
      </div>
      <div class="modal-body">
        <p>The search box uses the following syntax:</p>
        <pre>operator1:value1 operator2:value2 operator3:value3</pre>
        <p>
        The searcher combines multiple operators using boolean AND. 
        Dates and times are parsed using <a href="https://github.com/mojombo/chronic#examples" rel="external" target="_blank">Chronic</a>.
        When using a date or time, replace spaces with underscores so five days ago becomes <code>five_days_ago</code>. 
        When searching for a specific date or time, a range of a full day is used.
        Using <code>submitted:5_days_ago_at_5pm</code> would display all jobs submitted between 6 days ago at midnight and 5 days ago at midnight.
        </p>

        <br/>

        <p>The following operators are supported:</p>
        <table class="table">
          <tr>
            <th>Operator</th>
            <th>Description</th>
            <th>Examples</th>
          </tr>
          <tr>
            <td><b>id</b> or <b>job</b></td>
            <td>Job ID equal to</td>
            <td>id:12345<br/>job:6789</td>
          </tr>
          <tr>
            <td><b>state</b></td>
            <td>Job state equal to</td>
            <td>state:failed<br/>state:completed</td>
          </tr>
          <tr>
            <td><b>source</b> or <b>input</b></td>
            <td>Source file matches</td>
            <td>source:foo</br>input:bar.mp4</td>
          </tr>
          <tr>
            <td><b>destination</b> or <b>output</b></td>
            <td>Destination file matches</td>
            <td>destination:foo</br>output:bar.mp4</td>
          </tr>
          <tr>
            <td><b>file</b></td>
            <td>Source or destination file matches</td>
            <td>file:foo.bar</td>
          </tr>
          <tr>
            <td><b>preset</b></td>
            <td>Preset name matches</td>
            <td>preset:h264_1000</td>
          </tr>
          <tr>
            <td><b>host</b></td>
            <td>Host name matches</td>
            <td>host:host1</td>
          </tr>
          <tr>
            <td><b>submitted</b> or <b>created</b></td>
            <td>Job submitted on, uses <a href="https://github.com/mojombo/chronic#examples" rel="external" target="_blank">Chronic</a></td>
            <td>submitted:5_days_ago<br/>created:15_aug</td>
          </tr>
          <tr>
            <td><b>completed</b></td>
            <td>Job completed on, uses <a href="https://github.com/mojombo/chronic#examples" rel="external" target="_blank">Chronic</a></td>
            <td>completed:2_days_ago<br/>completed:3_jan_2012</td>
          </tr>
          <tr>
            <td><b>started</b></td>
            <td>Job started transcoding on, uses <a href="https://github.com/mojombo/chronic#examples" rel="external" target="_blank">Chronic</a></td>
            <td>started:3_days_ago<br/>started:yesterday</td>
          </tr>
        </table>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
    </div>
  </div>
</div>

codem-schedule/app/views/layouts/_menu.html.erb
<ul class="nav nav-list">
  <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>  
  <li class="<%= 'active' if current_page?(jobs_path) %>"><%= link_to "Jobs", jobs_path %></li>  
  <li class="<%= 'active' if current_page?(hosts_path) %>"><%= link_to "Hosts", hosts_path %></li>  
  <li class="<%= 'active' if current_page?(presets_path) %>"><%= link_to "Presets", presets_path %></li>  
</ul>

codem-schedule/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %> - Codem Scheduler</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render "/layouts/help" %>

<div class="frame">
  <div class="sidebar">
    <div class="wrapper">
      <%= render '/layouts/help' %>
      <%= render "/layouts/menu" %>
    </div>
  </div>

  <div class="content">
    <div class="navbar navbar-static-tops">
      <div class="navbar-inner">
        <%= link_to 'Codem', root_url, class: 'brand' %>
      </div>
    </div>

    <div class="content-head">
      <form action="<%= jobs_path %>" method="get" class="navbar-search pull-right">
        <%= search_field_tag 'q', params[:q], class: 'form-control search-query', placeholder: 'Search' %>
        <a href="#help" role="button" class="btn" data-toggle="modal">Help</a>
      </form>

      <h1 class="title"><%= link_to yield(:title), url_for(params.slice(:controller, :action)) %></h1>


      <div class="content-body">
      <% flash.each do |name, message| %>
        <div class="alert alert-block alert-<%= name %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= h message %>
        </div>
      <% end %>

      <%= yield %>


    </div>
  </div>
</div>

</body>
</html>