codem-schedule/config/routes.rb
Scheduler::Application.routes.draw do
  namespace :api do
    resources :jobs do
      collection do
        get :scheduled
        get :processing
        get :on_hold
        get :success
        get :completed
        get :failed
        delete :purge
      end

      member do
        post :retry
      end

      member do
        resources :state_changes
        resources :notifications
      end
    end

    get '/probe'   => 'api#probe'
    get '/schedule' => 'scheduler#schedule'

    resources :presets

    resources :hosts

    get '/statistics' => 'statistics#show'
  end

  resources :jobs

  resources :presets, :hosts

  root :to => 'dashboard#show'
end

codem-schedule/app/models/job.rb
class Job < ActiveRecord::Base
  include Jobs::States

  Scheduled   = 'scheduled'
  Processing  = 'processing'
  OnHold      = 'on_hold'
  Success     = 'success'
  Failed      = 'failed'

  belongs_to :preset
  belongs_to :host

  has_many :state_changes, -> { order('position ASC') }, dependent: :destroy
  has_many :notifications, dependent: :destroy

  before_destroy :remove_job_from_transcoder

  serialize :arguments

  scope :scheduled,   -> { where(state: Scheduled) }
  scope :processing,  -> { where(state: Processing) }
  scope :success,     -> { where(state: Success) }
  scope :on_hold,     -> { where(state: OnHold) }
  scope :failed,      -> { where(state: Failed) }

  scope :recent,      -> { includes([:host, :preset]) }

  scope :unfinished,  -> { where('state in (?)', [Processing, OnHold]) }
  scope :need_update, -> { where('state in (?)', [Processing, OnHold]) }

  validates :source_file, :destination_file, :preset_id, presence: true

  class << self
    def from_api(options)
      options = options[:job] if options[:job]

      args = {}
      options['arguments'].split(',').each do |arg|
        k, v = arg.split('=')
        args.merge!(k.to_sym => v)
      end if options['arguments']

      job = new(source_file: options['input'],
                destination_file: options['output'],
                preset: Preset.find_by_name(options['preset']),
                priority: options['priority'],
                notifications: Notification.from_api(options[:notify]),
                arguments: args)

      job.enter(Job::Scheduled) if job.save

      job
    end

    def recents(opts = {})
      jobs = all

      jobs = Job.search(opts[:query]) if opts[:query]

      jobs = jobs.recent.page(opts[:page])

      if opts[:sort] && opts[:dir]
        jobs = jobs.order('jobs.' + opts[:sort] + ' ' + opts[:dir])
      end

      jobs
    end

    def search(query)
      JobSearch.search(all, query)
    end
  end

  def needs_update?
    state == Processing || state == OnHold
  end

  def finished?
    state == Success || state == Failed
  end

  def unfinished?
    state == Scheduled || state == Processing || state == OnHold
  end

  private

  def remove_job_from_transcoder
    Transcoder.remove_job(self)
    true
  end
end

codem-schedule/app/models/jobs/states.rb
module Jobs
  module States
    def self.included(base)
      base.class_eval do
        before_create :set_initial_state
        after_create :create_initial_state_change
      end
    end

    def initial_state
      Job::Scheduled
    end

    def enter(new_state, params = {}, _headers = {})
      with_lock(true) do
        if state != new_state
          self.state = new_state

          create_state_change(params['message'])

          send("enter_#{new_state}", params)
          save
        end
      end

      self
    end

    def create_state_change(message = nil)
      state_changes.create!(state: state, message: message)
    end

    protected

    def set_initial_state
      self.state = initial_state
    end

    def create_initial_state_change
      create_state_change
    end

    def enter_scheduled(_params)
    end

    def enter_processing(params)
      update_attributes progress: params['progress'],
                        duration: params['duration'],
                        filesize: params['filesize']
      notify
    end

    def enter_on_hold(_params)
    end

    def enter_failed(params)
      update_attributes message: params['message']
      notify
    end

    def enter_success(params)
      update_attributes(
        completed_at: Time.current,
        message: params['message'],
        progress: 1.0
      )
      notify
    end

    def notify
      notifications.each { |n| n.notify!(job: self, state: state) }
    end
  end
end

codem-schedule/app/controllers/api/jobs_controller.rb
# = Jobs controller
#
# == States
# A job can be in one of the following states:
#
# <tt>scheduled</tt>::   Scheduled to be sent to the Transcoder instances
# <tt>processing</tt>::  Being processed by a Transcoder Instance
# <tt>\on_hold</tt>::    Waiting for a Transcoder to become responsive again
# <tt>success</tt>::     Successfully completed
# <tt>failed</tt>::      An error occurred
#
# == Pagination
# For methods that use pagination, a <tt>page</tt> parameters can be sent to display that particular page of jobs.
# Jobs are paginated with 25 jobs per page.
# For example, to get the 5th page of successfully completed jobs, use:
#   http://host.com/api/jobs/completed?page=5
module Api
  class JobsController < ApiController
    respond_to :rss, only: [:index, :scheduled, :processing, :on_hold, :success, :failed]
    # == Returns a list of jobs regardless of state.
    # This method uses pagination.
    def index
      jobs_index(Job.all)
    end
    # == Returns a list of scheduled jobs
    # Scheduled jobs are created, but not yet accepted by the transcoders.
    # This method uses pagination.
    def scheduled
      jobs_index(Job.scheduled)
    end
    # == Returns a list of jobs being processed.
    # Jobs being processed are being transcoded by a \Transcoder.
    # This method uses pagination.
    def processing
      jobs_index(Job.processing)
    end
    # == Returns a list of jobs that are on hold
    # Jobs will be put on hold when a \Transcoder instance is unavailable.
    # This method uses pagination.
    def on_hold
      jobs_index(Job.on_hold)
    end
    # == Returns a list of successfully completed jobs
    # These jobs have been successfully transcoded.
    # This method uses pagination.
    def success
      jobs_index(Job.success)
    end
    alias_method :completed, :success
    # == Returns a list of failed jobs
    # Jobs become failed if the \Transcoder reports an error.
    # This method uses pagination.
    def failed
      jobs_index(Job.failed)
    end

    # == Creates a job
    #
    # Creates a job using the specified parameters, which are all required. If the request was valid,
    # the created job is returned. If the request could not be completed, a list of errors will be returned.
    #
    # If the job is successfully created, two extra headers will be sent in the response.
    # The header <tt>X-State-Changes-Location</tt> contains the location of the state changes endpoint for this job.
    # The header <tt>X-Notifications-Location</tt> contains the location of the notifications endpoint for this job.
    #
    # === Parameters
    # <tt>input</tt>, <tt>output</tt> and <tt>preset</tt> are required parameters, <tt>notify</tt> is optional.
    # <tt>input</tt>:: Input file to process
    # <tt>output</tt>:: Output file to write to
    # <tt>preset</tt>:: Preset name to use
    # <tt>priority</tt>:: Priority as integer (default nil, maximum 999)
    # <tt>notify</tt>:: A list of email addresses and urls separated by commas.
    #
    # If a job enters the completed or failed state, a notification will be sent to the emails and urls specified in the
    # <tt>notify</tt> parameter. Urls will receive a POST request with the JSON representation of the job as body.
    #
    # === Response codes
    # <tt>success</tt>:: <tt>201 created</tt>
    # <tt>failed</tt>::  <tt>406 Unprocessable Entity</tt>
    #
    # === Example
    #   $ curl -d 'input=/tmp/foo.flv&output=/tmp/bar.mp4&preset=h264' http://localhost:3000/api/jobs
    #
    #   {
    #     "job": {
    #       "completed_at":null,
    #       "created_at":"2011-05-10T08:25:00Z",
    #       "destination_file":"/tmp/bar.mp4",
    #       "duration":null,
    #       "filesize":null,
    #       "host_id":1,
    #       "id":26,
    #       "message":null,
    #       "preset_id":1,
    #       "priority":null,
    #       "progress":null,
    #       "remote_job_id":"fa832776a64b6844fb9f1a244757734a9d83c00f",
    #       "source_file":"/tmp/foo.flv",
    #       "state":"scheduled",
    #       "transcoding_started_at":"2011-05-10T08:25:03Z",
    #       "updated_at":"2011-05-10T08:25:03Z"
    #     }
    #   }
    def create
      job = Job.from_api(params)
      if job.valid?
        response.headers['X-State-Changes-Location'] = api_state_changes_url(job)
        response.headers['X-Notifications-Location'] = api_notifications_url(job)
        respond_with job, location: api_job_url(job) do |format|
          format.html { redirect_to jobs_path }
        end
      else
        respond_with job do |format|
          format.html do
            @job = job
            render '/jobs/new'
          end
        end
      end
    end

    # == Updates a job with attributes from the transcoder
    #
    # This endpoint is specifically for updating a job from the transcoder and should not be called manually.
    def update #:nodoc:
      job = Job.find(params[:id])
      job.enter(params[:status], params, request.headers)
      respond_with job, location: api_job_url(job)
    end

    # == Shows a job
    #
    # The displayed job will have its status updated to provide an up-to-date view of attributes.
    #
    # === Parameters
    # <tt>id</tt>:: The id of the job to show
    #
    # === Example
    #   {
    #     "job": {
    #       "completed_at":null,
    #       "created_at":"2011-05-10T08:25:00Z",
    #       "destination_file":"/tmp/bar.mp4",
    #       "duration":null,
    #       "filesize":null,
    #       "host_id":1,
    #       "id":26,
    #       "message":null,
    #       "preset_id":1,
    #       "progress":null,
    #       "remote_job_id":"fa832776a64b6844fb9f1a244757734a9d83c00f",
    #       "source_file":"/tmp/foo.flv",
    #       "state":"scheduled",
    #       "transcoding_started_at":"2011-05-10T08:25:03Z",
    #       "updated_at":"2011-05-10T08:25:03Z"
    #     }
    #   }
    def show
      job = Job.find(params[:id])
      respond_with job
    end

    # == Purges failed jobs
    #
    # This method will permanently delete all failed jobs from the database.
    #
    #   $ curl -XDELETE http://localhost:3000/api/jobs/purge
    #   {} # HTTP Status: 200 OK
    def purge
      Job.failed.destroy_all
      render nothing: true
    end

    # == Retries a job
    #
    # This method will force a job into the Scheduled state, regardless of which state it's currently in.
    #
    # === Parameters
    # <tt>id</tt>:: The id of the job to retry
    def retry
      job = Job.find(params[:id])
      job.enter(Job::Scheduled)
      respond_with job do |format|
        format.html { redirect_to jobs_path }
      end
    end

    # == Deletes a job
    #
    # Removes a job from the database, regardless of state
    #
    # == Parameters
    # <tt>id</tt>:: The id of the job to destroy
    def destroy
      job = Job.find(params[:id])
      job.destroy
      respond_with job do |format|
        format.html { redirect_to jobs_path }
      end
    end

    private #:nodoc:

    def jobs_index(jobs)
      jobs = jobs.order('created_at DESC').page(params[:page])
      respond_with jobs
    end
  end
end

codem-schedule/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @history = History.new(params[:period])
    @jobs    = Job.recents(page: params[:page], sort: sort_column, dir: sort_direction, query: params[:q])
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end
end

codem-schedule/app/helpers/jobs_helper.rb
module JobsHelper
  def progress_as_percentage(progress)
    format '%.2f', (progress.to_f * 100.0)
  end

  def encoding_time(job)
    time = job.completed_at.to_i - job.transcoding_started_at.to_i
    time < 0 ? 0 : time
  end

  def destination_filesize(job)
    File.size(job.destination_file)
  rescue Errno::ENOENT
    'unknown (file gone)'
  end

  def notified_at(notification, job)
    return nil if notification.notified_at.blank?
    num = notification.notified_at.to_i - job.completed_at.to_i
    num <= 0 ? '00:00:00' : number_to_time(num)
  end

  def compression_rate(job)
    pct = (destination_filesize(job).to_f / job.filesize.to_f) * 100.0
    format '%.2f', pct
  end

  def number_to_time(seconds)
    return nil if seconds.to_i < 1
    time = Time.at(seconds).utc
    if seconds > 86_400
      days = seconds / 3600 / 24
      "#{format '%02d', days}:#{time.strftime('%H:%M:%S')}"
    else
      time.strftime('%H:%M:%S')
    end
  end
end

codem-schedule/app/views/jobs/_deliveries.html.erb
<tr id="deliveries_<%= state_change.id %>" style="display:none;">
  <td colspan="5">
    <table class="table" width="100%">
      <tr class="odd">
    		<th>Type</th>
    		<th>Value</th>
    		<th>State</th>
    	</tr>

      <% for delivery in state_change.deliveries %>
        <tr>
      		<td><%= delivery.try(:notification).try(:name) || 'no data' %></td>
      		<td><%= delivery.try(:notification).try(:value) || 'no data' %></td>
      		<td><%= delivery.state.titleize %> after <%= notified_at delivery, @job %></td>
      	</tr>	
      <% end %>
    </table>
  </td>
</tr>

codem-schedule/app/views/jobs/_job.html.erb
<%= content_tag_for :tr, job, :class => job.state do %>
  <td class="id center">
    <%= link_to job.id, job %>
  </td>
  <td class="input_file" title="<%= job.source_file %>">
    <%= File.basename job.source_file %>
  </td>
  <td class="duration center" title="<%= number_with_delimiter job.duration %> seconds">
    <%= number_to_time job.duration %>
  </td>
  <td class="size" title="<%= number_with_delimiter job.filesize %> bytes">
    <%= number_to_human_size job.filesize %>
  </td>
  <td class="submitted" title="<%= I18n.l job.created_at %>">
    <%= time_ago_in_words job.created_at %> ago
  </td>
  <td class="preset" title="<%= job.preset.try(:parameters) %>">
    <%= job.preset.try(:name) %>
  </td>
  <td class="host" title="<%= strip_tags host_name(job.host) if job.host %>">
    <%= job.host.try(:name) %>
  </td>
  <td class="state <%= job.state %>" title="<%= job.message %>">
    <%= state_label job.state %>
    
		<%- if job.state == Job::Processing -%>
      <div class="progress progress-striped active">
        <div class="bar" style="width:<%= progress_as_percentage job.progress %>%">
          <%= progress_as_percentage job.progress %>%&nbsp;
        </div>
      </div>
    <%- elsif job.state == Job::Failed -%>
      <%= button_to 'Retry', retry_api_job_path(job), :class => 'btn btn-mini' %>
    <%- end -%>

  </td>
	<td class="completed_after" title="<%= I18n.l job.completed_at if job.completed_at %> seconds">
		<%= number_to_time encoding_time(job) %>
	</td>
<% end %>

codem-schedule/app/views/jobs/_jobs.html.erb
<table class="table table-striped" id="jobs">
  <thead>
    <tr>
      <th class="center"><%= sortable 'id', 'Job ID' %></th>
      <th><%= sortable 'source_file', 'Input File' %></th>
      <th class="center"><%= sortable 'duration', 'Input duration' %></th>
      <th><%= sortable 'filesize', 'Input size' %></th>
      <th><%= sortable 'created_at', 'Submitted' %></th>
      <th><%= sortable 'preset_id', 'Preset' %></th>
      <th><%= sortable 'host_id', 'Host' %></th>
      <th><%= sortable 'state', 'Status' %></th>
			<th><%= sortable 'completed_at', 'After' %></th>
    </tr>
  </thead>
  
  <tbody id="item_list">
    <%= render @jobs %>
  </tbody>
  
</table>

codem-schedule/app/views/jobs/_notifications.html.erb
<% if @job.notifications.any? %>
  <table class="table">
	  <tr class="odd">
		  <th>Type</th>
		  <th>Value</th>
		  <th>State</th>
	  </tr>

	  <% for notification in @job.notifications %>

		  <tr>
			  <td><%= notification.name %></td>
			  <td><%= notification.value %></td>
			  <td><%= notification.state %></td>
		  </tr>

	  <% end %>

  </table>
<% else %>
  <p>No notifications</p>
<% end %>

codem-schedule/app/views/jobs/index.html.erb
<% title 'Jobs' %>

<%= section 'History' do %>
  <%= render "history" %>
<% end %>

<%= section 'Jobs' do %>
  <%= render "jobs" %>
  
  <%= will_paginate @jobs %>
<% end %>

<div class="form-actions">
  <%= link_to 'New job', new_job_path, :class => 'btn btn-primary' %>
</div>

codem-schedule/app/views/jobs/new.html.erb
<% title 'New job' %>

<%= form_tag api_jobs_path, class: 'form-horizontal' do %>
	
	<% if @job.errors.any? %>
    <div class="panel panel-warning">
      <div class="panel-heading">
        Job could not be saved
      </div>

      <div class="panel-body">
        <ul>
          <% @job.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

	<fieldset>
    <legend>Create a new job</legend>

    <div class="control-group">
      <%= label_tag :input, nil, class: 'control-label required' %>
      <div class="controls">
        <%= text_field_tag :input, @job.try(:source_file), class: 'form-control' %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag :output, nil, class: 'control-label required' %>
      <div class="controls">
        <%= text_field_tag :output, @job.try(:destination_file), class: 'form-control' %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag :preset, nil, class: 'control-label required' %>
      <div class="controls">
        <%= select_tag :preset, options_for_select(Preset.all.map { |p| [p.name] }, @job.try(:preset).try(:name)), class: 'form-control' %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag :priority, nil, class: 'control-label' %>
      <div class="controls">
        <%= text_field_tag :priority, @job.try(:priority), class: 'form-control' %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag :notify, nil, class: 'control-label' %>
      <div class="controls">
        <%= text_area_tag :notify, nil, rows: 3, class: 'form-control' %>
      </div>
    </div>

  </fieldset>
  
  <div class="form-actions"> 
    <%= submit_tag 'Create Job', class: 'btn btn-primary' %> or 
    <%= link_to 'Cancel', jobs_path %>
  </div>
  

<% end %>

codem-schedule/app/views/jobs/show.html.erb
<% title "View Job" %>

<%- @jobs = [@job] -%>

<%= render :partial => "jobs" %>

<h2>History</h2>

<table class="table">
	<tr class="odd">
		<th>State</th>
		<th>Occurred</th>
		<th>Message</th>
	</tr>
	<% for state_change in @job.state_changes %>
		<tr>
			<td>
			  <%= state_label state_change.state %>
			</td>
			<td title="<%= I18n.l state_change.created_at %>">
			  <%= time_ago_in_words state_change.created_at, :include_seconds => true %> ago
			</td>
			<td>
			  <%= state_change.message %>

			  <%- if state_change.deliveries.any? -%>
  			  <span class="notifications">
  			   <%= link_to pluralize(state_change.deliveries.size, 'notification'),
  			               '#',
  			               onclick: "$('#deliveries_#{state_change.id}').toggle()" %>
  			  </span>
			  <%- end -%>

			</td>
		</tr>

	  <%- if state_change.deliveries.any? -%>
	    <%= render :partial => "deliveries", :locals => {:state_change => state_change} %>
		<%- end -%>
	<% end %>

</table>

<h2>Notifications</h2>
<%= render "notifications" %>

<h2>Preset parameters</h2>
<pre><%= @job.preset.parameters rescue 'Preset not found' %></pre>

<% if @job.remote_job_id %>
  <h2>Delete job</h2>
  <%= link_to 'Delete job', api_job_path(@job), method: :delete, data: { confirm: 'Are you sure you want to delete this job?' }, class: 'btn btn-danger' %>
<% end %>